Repository TeamAraBook/AraBook-AI-Server, pull requests merged in 2024-10, with the labels that each got.

#12 [Feat] #11 - Open AI API연결 완료
  data/bestseller_data.xls
  main.py
  myenv/share/man/man1/isympy.1
Labels: 🌱 Feat, 🧸 가은

#15 [Feat] #14 - 카테고리 분류 함수 구현
  category_classifier.py
  data/bestseller_data.xls
  main.py
Labels: 🌱 Feat, 🧸 가은

#17 [Feat] #16 - 책 정보 크롤링 함수 구현
  crawling.py
  main.py
Labels: 🌱 Feat, 🧸 가은

#19 [Feat] #13 - Chroma DB 연결
  category_classifier.py
  chroma_db/chroma.sqlite3
  chroma_db/d10fbfbf-625c-4427-86c9-3c47d1dc7f21/data_level0.bin
  chroma_db/d10fbfbf-625c-4427-86c9-3c47d1dc7f21/header.bin
  chroma_db/d10fbfbf-625c-4427-86c9-3c47d1dc7f21/length.bin
  chroma_db/d10fbfbf-625c-4427-86c9-3c47d1dc7f21/link_lists.bin
  main.py
Labels: 🌱 Feat, 🧸 가은

#22 [Feat] #18 - isbn 입력 시 책 정보 및 해시태그, 카테고리 저장 로직 구현
  .gitignore
  book_info.py
  database_conn.py
  main.py
  myenv/share/man/man1/isympy.1
Labels: 🌱 Feat, 🦋 성은

#23 [Fix] #21 - 도서 카테고리 분류 문제 해결
  category_classifier.py
  main.py
Labels: 🎈 Fix, 🧸 가은

#25 [Chore] #24 - 도서 데이터 저장 방법 변경
  category_classifier.py
  chroma_db/6315917b-4f7c-4b2f-bbcc-47682d79be4b/header.bin
  chroma_db/6315917b-4f7c-4b2f-bbcc-47682d79be4b/length.bin
  chroma_db/6315917b-4f7c-4b2f-bbcc-47682d79be4b/link_lists.bin
  chroma_db/chroma.sqlite3
  chroma_db/d10fbfbf-625c-4427-86c9-3c47d1dc7f21/data_level0.bin
  chroma_db/d10fbfbf-625c-4427-86c9-3c47d1dc7f21/header.bin
  chroma_db/d10fbfbf-625c-4427-86c9-3c47d1dc7f21/length.bin
  chroma_db/d10fbfbf-625c-4427-86c9-3c47d1dc7f21/link_lists.bin
  chroma_manager.py
  main.py
Labels: ☂️ Chore, 🧸 가은

#26 [Feat] #20 - 도서 추천 API 구현
  .vscode/settings.json
  category_classifier.py
  chroma_db/6315917b-4f7c-4b2f-bbcc-47682d79be4b/length.bin
  chroma_db/chroma.sqlite3
  chroma_manager.py
  database_conn.py
  main.py
Labels: 🌱 Feat, 🧸 가은

#29 [Feat] #27 - 스케줄러 구현
  .DS_Store
  database_conn.py
  main.py
  scheduler.py
Labels: 🌱 Feat, 🧸 가은

#30 [Feat] #28 - 베스트 셀러 리스트 업데이트 스케줄러 구현
  .DS_Store
  book_info.py
  chroma_manager.py
  database_conn.py
  main.py
  scheduler.py
Labels: 🌱 Feat, 🦋 성은

#32 [Fix] #31 - 서버 실행 오류 해결
  category_classifier.py
  chroma_db/chroma.sqlite3
  chroma_manager.py
  main.py
  scheduler.py
Labels: 🎈 Fix, 🧸 가은
